### ISSUE TITLE
Trying to start server issue.

### ISSUE THREAD

**Issue by bigdogpete** [TunkDesign/NeMa#20] opened 2016-06-16 06:16 UTC
When entering the server from the dashboard to start the server. I get a lost connectivity. Then I get a message that says " Still Connecting, It's taking longer than expected."  and just sits there. I actually let it sit overnight and it was still the same when I got up in the morning. 

I tested all the ports after I started the server manually. (This is the .jar that NeMa created.) All the ports can be seen outside my network. 

Does anyone have a solution or a suggestion to where I can start to look if it is me. Thanks.

**Comment by daemonus** [comment] 2016-06-16 17:35
No solution sorry but I can confirm that I am having the exact same issue as you.

**Comment by TunkDesign** [comment] 2016-06-16 17:42
Sorry for the late response. If you could please leave the wrapper on, over the next few days, so I can do some troubleshooting, that'd be wonderful. I will get back to you as soon as possible!

**Comment by bigdogpete** [comment] 2016-06-16 21:15
I will leave it on. Saturday they are having a power outage. I will get it back online as soon as that is completed.

**Comment by bigdogpete** [comment] 2016-06-18 14:21
Wrapper back up. Still having problem.

**Comment by TunkDesign** [comment] 2016-06-18 14:26
@bigdogpete I will now temporarily move the wrapper to a testing environment to try and find the issue. Please keep it running.

**Comment by bigdogpete** [comment] 2016-06-18 14:32
Will do.

**Comment by TunkDesign** [comment] 2016-06-18 15:01
I have now checked the connection to the wrapper multiple times (as you might see in the wrapper console window). I've checked it on different connections, in different environments and with throttled connections. Everything worked just fine, which is odd.

I will need some more information to search deeper. What's your operating system, internet browser and internet connection speed?

Sorry for the inconvenience!

**Comment by daemonus** [comment] 2016-06-18 15:19
Im hosting on windows 10 using latest firefox to view panel. Internet speed
heres something like 1-2 megs/sec down and around 500kbps up. Everything
with the wrapper works fine, creating a server etc so I doubt its to do
with os, browser or internet speed.

If you need it I can give you remote access to my server to diagnose the
issue

**Comment by bigdogpete** [comment] 2016-06-18 16:07
CENTOS 7 X64 Build 1511. Firefox 45.2 (on the server)   or Chrome 51.0.2704.103 m (on my Rig). 

Depends but about 8 Mb/s up and 4 Mb/s Down.

**Comment by bigdogpete** [comment] 2016-06-18 18:55
I created a test server on the server named BigdogpeteTEST. In case you need to start one. I apologize that I was on it while you were testing.

**Comment by TunkDesign** [comment] 2016-06-18 19:18
@bigdogpete If you could accept the EULA, that would be awesome :)

**Comment by bigdogpete** [comment] 2016-06-18 19:21
Houston I figured out what the problem is but I don't know how to go about fixing it.
My Public address is an address outside my network. When trying to open the panel it asked my browser to go to ws://name-of-server.com:20000. This resulted in a connection refused. 

When I ran up my phone as a hotspot and connected with my laptop I was right in. I used the console on chrome.

**Comment by bigdogpete** [comment] 2016-06-18 19:22
EULA Accepted!

**Comment by TunkDesign** [comment] 2016-06-18 19:25
Thanks for accepting the EULA. I'll run a few tests, to make sure everything is working! 

Glad you found the issue. It seemed like something out of my control, and it looks like that's the case! I see the .us address you are using, and it could be the cause. I'll do some research :)

**Comment by bigdogpete** [comment] 2016-06-18 19:28
It is a DYNDNS address and then I have port forwarding on my ISP router. 

I am going to try to do an alternate address in the server area. Will let you know.

**Comment by TunkDesign** [comment] 2016-06-18 19:31
Do you want me to move the wrapper to your panel again? It is currently in my testing environment hahah

**Comment by bigdogpete** [comment] 2016-06-18 19:31
Yes let me try something and then I will hand back off to you.

**Comment by TunkDesign** [comment] 2016-06-18 19:32
There you go :)

**Comment by bigdogpete** [comment] 2016-06-18 19:40
Ok back to you. I do not know why you cannot reach 20021. 

My thought was to put the local IP as additional IP in the Wrapper settings. But the code on the panel page only allows us to try the first one. Perhaps you could add something in the code to try the secondary IP if the first one fails. Then let users know that if they have it in this config to add their local IP addresses to the additional IP area of the server tab.

Just a thought.

**Comment by bigdogpete** [comment] 2016-06-18 19:42
Sorry

DOMException: Blocked a frame with origin "https://www.youtube-nocookie.com" from accessing a cross-origin frame.(…)
server.js:1 [NEMA] Setting up connection variables..
server.js:1 [NEMA] Initiating WebSocket..
server.js:1 [NEMA] Connecting to server..
server.js:1 WebSocket connection to 'ws://bigdogpetemc01.land-4-sale.us:20000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
server.js:1 
server.js:1 [NEMA] Connection error. Event data:
server.js:1 [NEMA] {"isTrusted":true}
server.js:1 
server.js:1 [NEMA] Connection closed. Event data:
server.js:1 [NEMA] {}
server.js:1 [NEMA] Sorry for the delay. It is taking longer than expected..

**Comment by TunkDesign** [comment] 2016-06-18 20:01
Do you have the ports forwarded with the both TCP **and** UDP protocol? If not, try setting it to use both then try connecting to the server again.

**Comment by daemonus** [comment] 2016-06-18 21:48
Make sure you forward both the router and any software firewalls as well, I
had issues because I forgot to forward in windows firewall.

Re domain name, I am also using dynamic dns. We need it to go to localip if
run locally and external domain if run remotely, this should be possible, i
know how to code it in c# but thats not much use to ya :(

**Comment by bigdogpete** [comment] 2016-06-19 04:27
Both TCP and UDP are forwarded. Still no joy.

**Comment by daemonus** [comment] 2016-06-19 04:54
Do you have the nema.exe equivalent file unblocked in the firewall? Not
sure if cent has this concept but basically I forward the ports and allow
the exe to communicate as well. With just the ports forwarded and the exe
not unblocked my ports still appear closed.

**Comment by bigdogpete** [comment] 2016-06-19 06:04
The firewall on CENTOS does not work like that. It isn't a application firewall. Also I tested my ports to make sure they were open correctly.

**Comment by bigdogpete** [comment] 2016-06-20 04:13
FTP ISSUE LOG
[1767 | INFO | 18/06/2016 07:51:57 PM] 213.114.143.127:53403-[] FTP session opened (connect)
[1612 | INFO | 18/06/2016 07:51:57 PM] [FTP] 213.114.143.127 connected on port 53403
[1775 | DEBUG | 18/06/2016 07:51:57 PM] 213.114.143.127:53403-[] -> 220 This server is proudly powered by https://nemanager.com/
[1775 | DEBUG | 18/06/2016 07:51:57 PM] 213.114.143.127:53403-[] <- AUTH TLS
[1775 | DEBUG | 18/06/2016 07:51:57 PM] 213.114.143.127:53403-[] -> 500 Command "AUTH" not understood.
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[] <- AUTH SSL
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[] -> 500 Command "AUTH" not understood.
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[] <- USER BigdogpeteTEST3592
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[] -> 331 Username ok, send password.
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- PASS ******
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 230 Login successful.
[1767 | INFO | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] USER 'BigdogpeteTEST3592' logged in.
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- OPTS UTF8 ON
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 501 Invalid argument.
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- OPTS MLST type;perm;size;modify;unix.mode;unix.uid;unix.gid;
[1775 | DEBUG | 18/06/2016 07:51:58 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 200 MLST OPTS type;perm;size;modify;unix.mode;unix.uid;unix.gid;
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- PWD
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 257 "/" is the current directory.
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- TYPE I
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 200 Type set to: Binary.
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- PASV
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 227 Entering passive mode (10,0,116,147,168,159).
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] <- MLSD
[1775 | DEBUG | 18/06/2016 07:51:59 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] -> 150 File status okay. About to open data connection.
[130 | DEBUG | 18/06/2016 07:52:19 PM] [debug] call: close() (<scripts.filemanager.FileHandler (addr=213.114.143.127:53403, user=u'BigdogpeteTEST3592')>)
[130 | DEBUG | 18/06/2016 07:52:19 PM] [debug] call: close() (<pyftpdlib.handlers.PassiveDTP listening 10.0.116.147:0 at 0xa19520c>)
[1767 | INFO | 18/06/2016 07:52:19 PM] 213.114.143.127:53403-[BigdogpeteTEST3592] FTP session closed (disconnect).
[1612 | INFO | 18/06/2016 07:52:19 PM] [FTP] 213.114.143.127 disconnected from port 53403
[1767 | INFO | 18/06/2016 07:52:19 PM] 213.114.143.127:53406-[] FTP session opened (connect)
[1612 | INFO | 18/06/2016 07:52:19 PM] [FTP] 213.114.143.127 connected on port 53406
[1775 | DEBUG | 18/06/2016 07:52:19 PM] 213.114.143.127:53406-[] -> 220 This server is proudly powered by https://nemanager.com/
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[] <- AUTH TLS
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[] -> 500 Command "AUTH" not understood.
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[] <- AUTH SSL
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[] -> 500 Command "AUTH" not understood.
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[] <- USER BigdogpeteTEST3592
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[] -> 331 Username ok, send password.
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- PASS ******
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 230 Login successful.
[1767 | INFO | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] USER 'BigdogpeteTEST3592' logged in.
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- OPTS UTF8 ON
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 501 Invalid argument.
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- OPTS MLST type;perm;size;modify;unix.mode;unix.uid;unix.gid;
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 200 MLST OPTS type;perm;size;modify;unix.mode;unix.uid;unix.gid;
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- PWD
[1775 | DEBUG | 18/06/2016 07:52:20 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 257 "/" is the current directory.
[1775 | DEBUG | 18/06/2016 07:52:21 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- TYPE I
[1775 | DEBUG | 18/06/2016 07:52:21 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 200 Type set to: Binary.
[1775 | DEBUG | 18/06/2016 07:52:21 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- PASV
[1775 | DEBUG | 18/06/2016 07:52:21 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 227 Entering passive mode (10,0,116,147,163,241).
[1775 | DEBUG | 18/06/2016 07:52:21 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] <- MLSD
[1775 | DEBUG | 18/06/2016 07:52:21 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] -> 150 File status okay. About to open data connection.
[130 | DEBUG | 18/06/2016 07:52:41 PM] [debug] call: close() (<scripts.filemanager.FileHandler (addr=213.114.143.127:53406, user=u'BigdogpeteTEST3592')>)
[130 | DEBUG | 18/06/2016 07:52:41 PM] [debug] call: close() (<pyftpdlib.handlers.PassiveDTP listening 10.0.116.147:0 at 0xa0835ec>)
[1767 | INFO | 18/06/2016 07:52:41 PM] 213.114.143.127:53406-[BigdogpeteTEST3592] FTP session closed (disconnect).
[1612 | INFO | 18/06/2016 07:52:41 PM] [FTP] 213.114.143.127 disconnected from port 53406

**Comment by bigdogpete** [comment] 2016-06-20 06:10
Panel Issue: I tried it at work too. It also failed. I think the problem arises that the site is not truly proxying the ws: traffic. It is actually coming from your computer. It does not try to connect on a secondary IP.

**Comment by TunkDesign** [comment] 2016-06-20 07:24
@bigdogpete Alright! I'll take a good look at the client side code when I get home!

**Comment by TunkDesign** [comment] 2017-04-21 19:12
The bridge between the panel and the wrapper has since been reworked. I am marking this as solved and closing it. If this is still an issue, please open again. Thanks :)

**Closed by TunkDesign** 2017-04-21 19:12 UTC
Labels: Bug, Panel, Solved
