### ISSUE TITLE
Cannot Create Jar File on Server creation.

### ISSUE THREAD

**Issue by bigdogpete** [TunkDesign/NeMa#19] opened 2016-06-16 05:48 UTC
I accidently put the jar file in the wrong folder. I fixed the issue but created 4 phantom servers in the process. The problem is that you cannot just go in and delete the folder. The wrapper will not start. I got it to start by mkdir whatever the directory name was. I am unable to figure out how to delete the remnant servers from the server. The log says it is reverting changes but it does not seem to get them all.

Does anyone know how to get the remnants out of the server without having to rebuild?

CENTOS 7 1151

[1602 | WARNING | 15/06/2016 11:59:39 PM] Failed to create jar file!
Traceback (most recent call last):
  File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/commands.server", line 72, in create
  File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/shutil", line 119, in copy
  File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/shutil", line 82, in copyfile
IOError: [Errno 21] Is a directory: u'/home/{username}/jars/'
[1602 | WARNING | 15/06/2016 11:59:39 PM] Server creation failed! Reverting changes!

**Comment by TunkDesign** [comment] 2016-06-16 17:48
If you don't want to start over, you can use a Sqlite database editor to modify your wrapper database file.

Thank you for the error log! I will look into why this is happening!

**Comment by bigdogpete** [comment] 2016-06-17 00:44
Just for clarification. That is the file nema.db in the DATA folder?

**Comment by TunkDesign** [comment] 2016-06-17 02:15
That's correct! :)

**Comment by daemonus** [comment] 2016-06-17 04:16
I had this issue as well! 

Two ways to reproduce:

**Method 1 - By deleting the server folder when the wrapper is not running.**

1. - Create a server in the panel
2. - Stop Wrapper
3. - Delete the folder created on the server by wrapper
4. - Restart Wrapper
5. - Wrapper crashed with error message. *

**Method 2 - By having no server jars in the jars folder when you try to create a server.**
(I have suspicions this is caused by any error in the process of creating a server, its not cleaning up after itself properly ;p)

1. - On the server make sure the **/jars/** folder is empty.
2. - Create a server in panel. Leave jars dropdown empty.
3. - Restart Wrapper
4. - Wrapper crashed with error message. *

* Output is something like the below. This is a hard crash (unhandled exception or whatever you call it in python) I had to screenshot the window as it closed to get the error details. The log has no record of this error, need to make sure its written to the logs to make this way easier to debug :)

Starting Wrapper..
Traceback (most recent call last):
File "<string>", line 56, in <module>
File "C:\TunkDesign\Build\NeMa\out00-PYZ.pyz\scripts.filemanager", line 60, in __init__
File "C:\TunkDesign\Build\NeMa\out00-PYZ.pyz\pyftpdlib.authorizers", line 106, in add_user
Value Error: no such directory: u'C:\\Minecraft\\test\\nemanager/servers/test-server/'

**I did manage to fix it by modifying the db using SqlLiteManager for Firefox**, I've worked with sqlite before though so not sure how easy this is for people! Just removed the entry in the 'server' table for the deleted server.

I also managed to fix it by recreating the directory that the wrapper was expecting.

**Comment by TunkDesign** [comment] 2016-06-18 07:07
@daemonus I really appreciate your detailed bug report! I will use that information to hopefully find a fix today!

**Comment by TunkDesign** [comment] 2016-06-18 19:13
These issues should now be resolved in the latest release (_v2.1.1_) :)

**Closed by TunkDesign** 2016-06-18 19:13 UTC
Labels: Bug, Solved, Wrapper
