### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by melerpe** [TunkDesign/NeMa#26] opened 2016-07-01 19:32 UTC
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/threading", line 810,  __bootstrap_inner
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/threading", line 763,  run
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.process", line06, in console
> ValueError: unsupported format character '!' (0x21) at index 19
> [DEBUG] http://panel.nemanager.com disconnected from port 61478
> Traceback (most recent call last):
>   File "<string>", line 58, in <module>
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.wrapper", line 262, in init
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.websocket", line 567, in run
> select.error: (4, 'Interrupted system call')
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/threading", line 810,  __bootstrap_inner
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/threading", line 763,  run
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.process", line06, in console
> ValueError: unsupported format character '!' (0x21) at index 19
> [DEBUG] http://panel.nemanager.com disconnected from port 61478
> Traceback (most recent call last):
>   File "<string>", line 58, in <module>
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.wrapper", line 262, in init
>   File "/TunkDesign/Build/NeMa/build/NeMa/out00-PYZ.pyz/scripts.websocket", line 567, in run
> select.error: (4, 'Interrupted system call')

**Comment by B3H1NDu** [comment] 2016-07-01 20:43
I'm going to ask you these questions so trunkdesign doesn't have to. What operating system are you running and what did you do leading up to the error, and what were you trying to achieve?

**Comment by melerpe** [comment] 2016-07-02 06:19
Centos 6.
Just starting a server.

**Comment by TunkDesign** [comment] 2016-07-02 17:02
Thank you for the traceback. I will see if I can find the cause and get back to you asap! Sorry for the inconvenience!

**Comment by TunkDesign** [comment] 2016-07-02 17:06
Just out of curiosity, does the log file say anything? It would help a tonne!

**Comment by TunkDesign** [comment] 2017-04-22 14:25
Closing this and marking it as invalid as I can't replicate it without proper information. If this is still an issue, please let me know! :)

**Closed by TunkDesign** 2017-04-22 14:25 UTC
Labels: Bug, Invalid, Linux, Wrapper
